=== nack-fs/F1Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="circuitos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="circuito" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="circuito">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
                <xs:element ref="longitudGlobal" />
                <xs:element ref="anchuraGlobal" />
                <xs:element ref="fecha" />
                <xs:element ref="hora" />
                <xs:element ref="localidad" />
                <xs:element ref="pais" />
                <xs:element ref="vueltas" />
                <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
                <xs:element minOccurs="1" maxOccurs="5" ref="imagen" />
                <xs:element minOccurs="0" maxOccurs="3" ref="video" />
                <xs:element ref="coordenada" />
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="nombre" type="xs:string" />

    <xs:element name="longitudGlobal">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="unidad" type="xs:string" default="metros" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="anchuraGlobal">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="unidad" type="xs:string" default="metros" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="fecha">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:date">
                    <xs:attribute name="formato" type="xs:string" default="ISO-8601" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="hora">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="referencia" type="xs:string" use="required" />
                    <xs:attribute name="formato" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="localidad">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="cp" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="pais" type="xs:string" />

    <xs:element name="referencia">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="URL" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="imagen">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="href" type="xs:string" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="video">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="href" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="coordenadaType">
        <xs:sequence>
            <xs:element name="longitud" type="xs:double" />
            <xs:element name="latitud" type="xs:double" />
            <xs:element name="altitud" type="xs:double" />
        </xs:sequence>
        <xs:attribute name="unidad" type="xs:string" />
    </xs:complexType>

    <xs:element name="coordenada" type="coordenadaType" />

    <xs:element name="punto">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="coordenada" />
            </xs:sequence>
            <xs:attribute name="distancia" type="xs:double" use="required" />
            <xs:attribute name="nSector" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="vueltas" type="xs:int" />
</xs:schema>

=== nack-fs/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuitos xmlns="http://www.uniovi.es"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

    <circuito>
        <nombre>Circuit de Barcelona-Catalunya</nombre>
        <longitudGlobal unidad="kilometros">4657</longitudGlobal>
        <anchuraGlobal unidad="metros">12</anchuraGlobal>
        <fecha formato="dd-mm-yyyy">2024-06-02</fecha>
        <hora referencia="CEST-Madrid" formato="24H">16:00</hora>
        <localidad cp="08160">Montmeló</localidad>
        <pais>España</pais>
        <vueltas>66</vueltas>

        <referencia URL="https://www.mundodeportivo.com/solomoto/20100630/1002107785/gp-cataluna-datos-tecnicos-informacion-util-montmelo.html">Información Técnica</referencia>
        <referencia URL="https://www.circuitcat.com/es/">Página Web Oficial</referencia>
        <referencia URL="https://www.circuitcat.com/es/circuit-de-catalunya/quienes-somos-2/">Contacto</referencia>

        <imagen href="multimedia/Img_Plano_Circuito.png">Mapa Circuito</imagen>
        <imagen href="multimedia/Img_Aerea_Circuito.png">Imagen Áerea</imagen>
        <imagen href="multimedia/Img_Carrera_2023.png">Carrera 2023</imagen>

        <video href="multimedia/Recording_GP.mp4">Video Pista</video>

        <coordenada>
            <longitud>2.261219193083508</longitud>
            <latitud>41.57002187570426</latitud>
            <altitud>120</altitud>
        </coordenada>

        <punto distancia="1141" nSector="1">
            <coordenada>
                <longitud>2.261219193083508</longitud>
                <latitud>41.57002187570426</latitud>
                <altitud>120</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.256836475849877</longitud>
                <latitud>41.56478814213454</latitud>
                <altitud>119</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.255632916268859</longitud>
                <latitud>41.56489697449817</latitud>
                <altitud>120</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.254915330521836</longitud>
                <latitud>41.56472657013462</latitud>
                <altitud>118</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.2540812726348</longitud>
                <latitud>41.56425754387585</latitud>
                <altitud>113</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.253502764384017</longitud>
                <latitud>41.56420112335872</latitud>
                <altitud>112</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.253023242229812</longitud>
                <latitud>41.56424747020185</latitud>
                <altitud>113</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.252515046883568</longitud>
                <latitud>41.56454621448057</latitud>
                <altitud>116</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.252152703768675</longitud>
                <latitud>41.56515380737703</latitud>
                <altitud>119</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.252206394122558</longitud>
                <latitud>41.56590297505895</latitud>
                <altitud>121</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.252771931548188</longitud>
                <latitud>41.56673194446256</latitud>
                <altitud>123</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.253447005676985</longitud>
                <latitud>41.5675301573928</latitud>
                <altitud>126</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.253786253800938</longitud>
                <latitud>41.56794287621663</latitud>
                <altitud>127</altitud>
            </coordenada>
        </punto>

        <punto distancia="1482" nSector="2">
            <coordenada>
                <longitud>2.253756849310475</longitud>
                <latitud>41.56790900790294</latitud>
                <altitud>127</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.254110059244556</longitud>
                <latitud>41.56830750996974</latitud>
                <altitud>129</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.254483576122523</longitud>
                <latitud>41.5684408691837</latitud>
                <altitud>130</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.254936284761899</longitud>
                <latitud>41.56838099315206</latitud>
                <altitud>140</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.255264536129766</longitud>
                <latitud>41.56815396121941</latitud>
                <altitud>141</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.255379521137681</longitud>
                <latitud>41.56770516333273</latitud>
                <altitud>132</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.25528719539603</longitud>
                <latitud>41.56723628818753</latitud>
                <altitud>132</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.254691363951646</longitud>
                <latitud>41.56652873968672</latitud>
                <altitud>133</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.254189753287121</longitud>
                <latitud>41.56597419708157</latitud>
                <altitud>133</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.253947746579328</longitud>
                <latitud>41.56559390863188</latitud>
                <altitud>130</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.254076820178637</longitud>
                <latitud>41.56539529391794</latitud>
                <altitud>129</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.254367994729467</longitud>
                <latitud>41.56531564363316</latitud>
                <altitud>128</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.254901968200826</longitud>
                <latitud>41.56544790317412</latitud>
                <altitud>126</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.256392855221785</longitud>
                <latitud>41.56595594060023</latitud>
                <altitud>125</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.257009701704837</longitud>
                <latitud>41.56637859314357</latitud>
                <altitud>123</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.257580412292486</longitud>
                <latitud>41.56702229182031</latitud>
                <altitud>120</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.257836364388404</longitud>
                <latitud>41.56743407182891</latitud>
                <altitud>118</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.257500684199778</longitud>
                <latitud>41.56776710913203</latitud>
                <altitud>122</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.256969284077632</longitud>
                <latitud>41.56807742332141</latitud>
                <altitud>134</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.255999386557614</longitud>
                <latitud>41.5698249411015</latitud>
                <altitud>136</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.25603763489669</longitud>
                <latitud>41.57022930776701</latitud>
                <altitud>137</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.256239232216948</longitud>
                <latitud>41.57046855025052</latitud>
                <altitud>136</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.257527433014561</longitud>
                <latitud>41.57102668456513</latitud>
                <altitud>133</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.260228815789813</longitud>
                <latitud>41.57206915274752</latitud>
                <altitud>133</altitud>
            </coordenada>
        </punto>

        <punto distancia="1309" nSector="3">
            <coordenada>
                <longitud>2.2602148121321</longitud>
                <latitud>41.57203760081947</latitud>
                <altitud>130</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.261837909724889</longitud>
                <latitud>41.57266872330411</latitud>
                <altitud>129</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.262018330264917</longitud>
                <latitud>41.57288277729682</latitud>
                <altitud>128</altitud>
            </coordenada>
            <coordenada>
                <longitud>2.261853811854742</longitud>
                <latitud>41.5732051577588</latitud>
